### ISSUE TITLE
a question regarding time_grouped.index%3e8==0

### ISSUE THREAD

**Issue by Tulin2010** [ama66843/ConvolutionalCloudWorkloadAnalysis#1]
Hi,
Thank you for posting the code for this respiratory. I have a question, what does this mean (time_grouped.index%3e8==0 )? so you divided the index by 3e8? i do not understand why? could you explain it for me, please.

**Comment by austinnottexas** [comment]
I plotted the CPU readings against the time of the measurement, and saw that the vast majority of readings came from those steps divisible by 3e08. Removing the small number of readings in between also ensured that all steps in time were equidistant.
